apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      containers:
        - name: welcome-container
          image: <public_registry_url>/testing/welcome:${{ github.ref }}
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: welcome-config
            - secretRef:
                name: welcome-secret
